services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - app-network-dev
    restart: always

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend-dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - app-network-dev
    restart: always

networks:
  app-network-dev:
    driver: bridge
